### PR TITLE
Q17-18-19

### PR DESCRIPTION
**Pull request by koriavinash1**

### CODE REVIEW

**Comment by markvdw** [comment]
Q17:
- We try to use capitals for RVs. Can you use lowercase $x$ for the vector? You can define it to be $\in \mathbb R^N$, and/or make it bold.
- First sentence: Use a phrasing like "Our model assumes a Gaussian probability density on the data of ...". We are not using a prior here.
- I'm not sure why you're using the prime behind parameters? I.e. why are you denoting $\mu'$ instead of just $\mu$?
- Your derivation of $\sigma$ is correct, but it's easier to just take the derivative w.r.t. $\sigma^2$. Could you do this instead? Also, for later in the course, it's more helpful to directly estimate the variance, since we want to discuss unbiasedness.
- You can use $\argmax$ to use the correct font. Currently it renders in italic, which is what is used for variables.
- Part a) was supposed to only be deriving the probability distribution with the product in it, due to the iid nature. Part b) was supposed to do the maximum likelihood. 
- Could you adjust the question accordingly to ask for the MaxLik estimate of \mu and \sigma^2 simultaneously? Since you already derived both? However, one change is necessary, you need to start by asking for $\mathrm{argmax}_{\mu,\sigma^2}$, since if you want to estimate them both, you have to estimate them jointly. Then you also need to verify that you have found a minimum by considering the Hessian of this multivariate function.

**Comment by markvdw** [comment]
Q18:
- Similar vector notation. You could use $\mat X$ for the matrix of all inputs X, and \vy for all the outputs.
- Otherwise, looks good. But for formatting, I would remove the big function from the partial derivative fraction. And I would create a feature vector that has a 1 appended to it, so you don't have to consider two parameters. I.e. all parameters including the bias can be kept in a single parameter vector \theta.

**Comment by markvdw** [comment]
Q19:
- Qa: bracket missing
- Can you add context saying that you use the quotient rule? Can you also derive with just the chain rule?

**Comment by koriavinash1** [comment]
I'll make these changes and push in some time.

In Q17, I use prime behind the parameters to differentiate between the parameters of infinite taled gaussian and the parameters of N sample gaussian. I thought part (a) would be incomplete without the parameter estimation.

In Q19, I'll add intermediate steps to avoid confusion

**Comment by markvdw** [comment]
Q17:
Hmm, I think I understand. What I meant with the question was that the Gaussian we specify in the question was the *model* not the data generating distribution. The question does not address any possible misspecification. So in my mind, the \mu and \sigma^2 were the values to be estimated. Do you think we should adapt the wording of the question?

My intention was for part a to only ask for the probability density implied for a sample of N variables. So my intention was not for including parameter estimation. I'm happy to adjust the wording of the question.

What do you think?

**Comment by koriavinash1** [comment]
In that case, I think, it would be clear (atleast for me)  if the term derive was rephrased to simplify the joint distribution or something else. Or, we can just remove the subparts and ask to derive the distribution (which includes both simplification and mle)

**Comment by markvdw** [comment]
I had to make a few additional edits, so I made a new PR. See https://github.com/markvdw/mml-autumn-2022/pull/32.

**Pull request closed without merging**
