### PR TITLE
Q15 and q16

### PR DESCRIPTION
**Pull request by charlio23**
ready to merge

### CODE REVIEW

**Comment by csegarragonz** [comment]
Hi, I have a couple of issues with the dimensions in this exercise.

First, should equation (11) be:

```math
p(\textbf{y} \vert \textbf{\theta}, X) = \mathcal{N}\left( \textbf{y}; \textbf{\theta}^T X, \sigma^2 Id \right)
```

**Comment by charlio23** [comment]
> Hi, I have a couple of issues with the dimensions in this exercise.
> 
> First, should equation (11) be:
> 
> ```
> p(\textbf{y} \vert \textbf{\theta}, X) = \mathcal{N}\left( \textbf{y}; \textbf{\theta}^T X, \sigma^2 Id \right)
> ```

By Eq. 11 you mean the one in question 16? I think it should be with X rather than \textbf{x}. The former has been used in the solutions.

Now that you mention the dimensions, I think there is a typo in the X \in R^ N x D part, as it should be D x N from Eq. 11. Is that so?

**Comment by csegarragonz** [comment]
Yes, I was writing that and forgot to finish.... 

I agree with you, the solution is OK, the statement needs rephrasing:
* It should be a capital X
* X should be in DxN indeed.

**Comment by markvdw** [comment]
I agree, ready to merge! Feel free to press the button after merging in `main`.

Actually, perhaps one thing I would change beforehand: I would suggest you punctuate your maths. Write as though the maths is part of the sentence. So you have something like "Thus, \begin{align} stuff **\,.**\end{align}"

**Pull request merged**
