### PR TITLE
working on q4, q5 and q6

### PR DESCRIPTION
**Pull request by tychovdo**

### CODE REVIEW

**Comment by tychovdo** [comment]
added answers to q4, q5 and q6

**Comment by markvdw** [comment]
This looks good. Few small changes:
- Can you pull in the latest `main`?
- Q4: Can you add a note to the students saying that they should know how to justify each step? E.g. "disjoint sets" for the union question, and a note that they should be able to prove the variance => expectation identity.
- Q5c: Can you state the elements which you're summing over, like you did in Q4?

**Comment by markvdw** [comment]
Q6a: Can you be explicit about the multiple integrals from the start? (First integral with limits \infty)
Q6b: Can you add some explanation how you get to this integral? Explain that you need to integrate over the full set of outcomes for Y, since specification allows for Y to take any value. This effectively tricks the students to derive the sum rule from first principles :)

**Comment by tychovdo** [comment]
Added extra explanations to Q6

**Comment by markvdw** [comment]
Merged in https://github.com/markvdw/mml-autumn-2022/pull/33.

**Pull request closed without merging**
